[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://ece-gate-academy-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://ece-gate-academy-backend.onrender.com/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  force = true